spring.application.name=user-service
spring.config.import=optional:file:.env[.properties]

server.port=${APPLICATION_PORT:3000}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/scrumdapp}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:myuser}
spring.datasource.password=${DATABASE_PASSWORD:secret}

passport.jwk-set-uri=${JWK_SET_URI:http://localhost:9999/.well-known/jwks.json}
